-- kolon seviyesinde subquery örneði(kolon yerine select sorgusu yazýyorsun)
SELECT 
E.EMPLOYEE_ID,E.LAST_NAME,
(SELECT D.DEPARTMENT_NAME FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID) "DEPARTMENT NAME"
FROM EMPLOYEES E;


--Tablo seviyesinde subquery örneði(tablo ismi yerine select sorgusu yazýyorsun)
SELECT REGION_NAME,COUNTRY_NAME FROM 
    (SELECT 
     R.REGION_ID,R.REGION_NAME,C.COUNTRY_ID,C.COUNTRY_NAME
     FROM REGIONS R JOIN COUNTRIES C ON R.REGION_ID=C.REGION_ID)
WHERE REGION_NAME= 'Europe';

--WHERE içinde subquery örneði
SELECT 
LAST_NAME,TO_CHAR(HIRE_DATE) "GÝRÝÞ TARÝHÝ"
FROM EMPLOYEES 
WHERE HIRE_DATE > (SELECT HIRE_DATE FROM EMPLOYEES WHERE EMPLOYEE_ID = 103);
     
SELECT 
FIRST_NAME,LAST_NAME,JOB_ID,SALARY
FROM EMPLOYEES WHERE SALARY =(SELECT MIN(SALARY) FROM EMPLOYEES);


--HAVING  seviyesinde subquery kullanýmý
SELECT 
DEPARTMENT_ID,
MIN(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MIN(SALARY) > (SELECT MIN(SALARY) FROM EMPLOYEES WHERE department_ýd = 100);


--CREATE TABLE komuutu (EMPLOYEES tablosundaki verileri yeni tablomuza aktardýk)
CREATE TABLE EMPLOYEES2 AS SELECT * FROM EMPLOYEES;

--ROWID bir satýrýn fiziksel adresini verir
SELECT ROWID,LAST_NAME,SALARY FROM EMPLOYEES;


--tekrar eden soyadý varsa listeledik
SELECT LAST_NAME,COUNT(*) 
FROM EMPLOYEES2
GROUP BY LAST_NAME
HAVING COUNT(*) >1;

--Tekrar eden soyadý kayýtlarý varsa hepsini sildik.
DELETE FROM EMPLOYEES2 
WHERE ROWID NOT IN(SELECT MAX(ROWID) FROM EMPLOYEES2 GROUP BY LAST_NAME);



