SELECT * FROM DEPARTMENTS;

CREATE TABLE DEPT1 AS SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID <= 160;

CREATE TABLE DEPT2 AS SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID >= 100;

--iki tabloyu birleþtirdi tablolarý olduðu gibi listeledi
SELECT * FROM DEPT1
UNION ALL
SELECT * FROM DEPT2;

--iki tabloyu birleþtirdi ve her kaydý bir kere listeledi
SELECT * FROM DEPT1
UNION 
SELECT * FROM DEPT2;